[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 8501
baseUrlPath = ""
maxUploadSize = 200
enableWebsocketCompression = false
maxMessageSize = 200

[theme]
primaryColor = "#A682FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F3FF"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false